version: '3.8'
services:
  api:
    build: .
    container_name: nestjs-api
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules